name: "Iconv"

on:
  pull_request:
  push:

jobs:
  iconvtest:
    name: "Iconv"
    runs-on: "ubuntu-latest"
    steps:
      - name: "Install PHP"
        uses: shivammathur/setup-php@2.11.0
        with:
          php-version: 7.4
          extensions: mbstring, iconv, intl

      - name: See if iconv fails
        run: |
          php -r '$r = iconv("UTF-8", "ASCII//TRANSLIT", "a 日本人"); echo $r; die($r ? 0 : 1);'
